# This is a basic workflow to help you get started with Actions

name: Collect Share Link

# Controls when the workflow will run
on:
  # Run script per hour
  schedule:
    - cron: '* */1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.9.14
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.14
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Update share list
        run: |
          python v2raySubs.py
        
      - name: Commit
        run: |
          git config --global user.email clovermoling@gmail.com
          git config --global user.name Crystal-Moling
          git add .
          git commit -m "update" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.COMMIT_TOKEN }}
